### ISSUE TITLE
When I tried to use it within my app, it just couldn't load in my application, giving me module error..

### ISSUE THREAD

**Issue by maddy2308** [shuyu/angular-material-fileinput#5]
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=FileUpload&p1=Error…udflare.com%2Fajax%2Flibs%2Fangular.js%2F1.4.7%2Fangular.min.js%3A19%3A463)

**Comment by shuyu** [comment]
Hi ~ That sound weird. Can you provide some code detail for me ?

**Comment by cristianciofu** [comment]
Hello @maddy2308 

You are having this issue because `angular-material-fileinput` depends on *Angular Material*. 

When bower installs your dependencies it also install these, so all you have to do in order to get rid of that error is to add them to your app ;)

```html
<script src="public/lib/angular-animate/angular-animate.min.js"></script>
<script src="public/lib/angular-aria/angular-aria.min.js"></script>
<script src="public/lib/angular-material-icons/angular-material-icons.min.js"></script>
<script src="public/lib/angular-material/angular-material.min.js"></script>
```

PS : @shuyu - I think it's a good idea to also specify this on the README :+1:

**Comment by shuyu** [comment]
Thank you for your advice !!  I really appreciate it !!
